// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketsCatalog.Repository;

#nullable disable

namespace TicketsCatalog.Migrations
{
    [DbContext(typeof(TicketsCatalogDataContext))]
    partial class TicketsCatalogDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("TicketsCatalog.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = "TK001",
                            Price = 1.3,
                            ValidFrom = new DateTime(2022, 7, 20, 14, 55, 12, 235, DateTimeKind.Utc).AddTicks(7731)
                        },
                        new
                        {
                            TicketId = "TK002",
                            Price = 1.5,
                            ValidFrom = new DateTime(2022, 7, 20, 14, 55, 12, 235, DateTimeKind.Utc).AddTicks(7734)
                        },
                        new
                        {
                            TicketId = "TK003",
                            Price = 2.2999999999999998,
                            ValidFrom = new DateTime(2022, 7, 20, 14, 55, 12, 235, DateTimeKind.Utc).AddTicks(7736)
                        },
                        new
                        {
                            TicketId = "TK004",
                            Price = 5.5,
                            ValidFrom = new DateTime(2022, 7, 20, 14, 55, 12, 235, DateTimeKind.Utc).AddTicks(7736)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
