// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVM.Repository;

#nullable disable

namespace TVM.Migrations
{
    [DbContext(typeof(TvmDataContext))]
    partial class TvmDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("TVM.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = "TK001",
                            Price = 1.3,
                            ValidFrom = new DateTime(2022, 7, 22, 8, 6, 32, 358, DateTimeKind.Utc).AddTicks(649)
                        },
                        new
                        {
                            TicketId = "TK002",
                            Price = 1.5,
                            ValidFrom = new DateTime(2022, 7, 22, 8, 6, 32, 358, DateTimeKind.Utc).AddTicks(656)
                        },
                        new
                        {
                            TicketId = "TK003",
                            Price = 2.2999999999999998,
                            ValidFrom = new DateTime(2022, 7, 22, 8, 6, 32, 358, DateTimeKind.Utc).AddTicks(657)
                        },
                        new
                        {
                            TicketId = "TK004",
                            Price = 5.5,
                            ValidFrom = new DateTime(2022, 7, 22, 8, 6, 32, 358, DateTimeKind.Utc).AddTicks(657)
                        });
                });

            modelBuilder.Entity("TVM.Models.TicketSale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("SaleId");

                    b.ToTable("TicketSales");
                });
#pragma warning restore 612, 618
        }
    }
}
